[build]
  command = "npm run generate"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/hint/*"
  to = "/.netlify/functions/server/hint/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/submit"
  to = "/.netlify/functions/server/submit"
  status = 200
  force = true
